### ISSUE TITLE
[EPIC] Stream Pipeline

### ISSUE THREAD

**Issue by dmetasoul01** [lakesoul-io/LakeSoul#170]
Pipeline refers to the data warehouse modeling process, such as building ODS (operation data store), DWD (data warehouse detail) layers to maximize the reuse of data and processing logics and standardize data assets in an organization.

Traditionally, for T+1 data warehouse, such modeling process was a set of SQL jobs that forms a DAG, and a scheduling system such as Airflow to run the DAG.

However the problems raise in realtime data warehouse modeling process:
* How do we write the modeling process?
* How to make the layered modeling process incremental and realtime?
* How to schedule the pipeline?

In this project we propose LakeSoul Stream Pipeline that provides:

Incremental read for both batch and streaming, and for both appended and upserted data;
* APIs for performing incremental compute and storage update, such as project/filter, aggregation (including high cardinality aggregation like distinct), stream-stream join, stream-batch join without compute engine's states, etc;
* Streams from different jobs can be coordinated. E.g. two incremental join-upsert streams (may be in two flink jobs) with same target table would have same pace to read incremental data.
* Multiple choices of sources and sinks;
* End-to-end exactly once;
* Pipeline as code with mixed yaml and sql (similar to dbt?).

Stream pipeline would include implementation related to both Flink and Spark. For Flink, we would implement dynamic table source with both batch (bounded) and stream (unbounded) mode. In Flink we would also support CDC stream read for LakeSoul's CDC table, so that the entire pipeline can be incremental.

Each layer of the pipeline is called a step. A pipeline could have multiple steps. Steps include common operations like filtering, aggregation, join and SQL. Steps could also be sinks with different targets.

Tasks:
- [x] Basic step config definition
- [x] Basic step implementations for filtering, aggregation, distinct and stream-batch join
- [ ]  Spark delta Stream-stream join (depends on #169 )
- [ ] Flink dynamic table source with batch, stream and cdc
- [ ] High cardinality aggregation
- [ ] Python Interface
- [ ] SQL rewrite
